### ISSUE TITLE
Hotkeys to change CD/floppy

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/pcem#3]
I think this workflow would be ideal:

`CD_path_var = file1.ext;file2.ext;file3.ext`

In the `cfg` file for a given machine (the variable being whatever PCem uses for a changeable image path, delimiter being whatever char fits best). This would queue 3 file paths in a given order.

Since the order to actually load the images in may be unknown in advance (routing out image order could be done while doing a test tas), we seem to need 2 keys to **select** "next" and "previous", and one command to **load** the currently selected image,

Also since PCem has 1 CD drive and 2 floppy drives, we seem to need 3 sets of those commands, 3 for each drive.

Finally, we need PCem to print to console which image was selected and which image was loaded. When it first loads the queue, probably print it all out so it's obvious what we're working with.

**Comment by vadosnaprimer** [comment]
To allow easier route testing while recording a movie, it was suggested to use a different approach.

Have keys to *select* next or previous image in the queue, and a separate key to load the one that's selected, while printing what was selected and what was loaded.

**Comment by clementgallet** [comment]
Could you suggest which keys to use?

**Comment by vadosnaprimer** [comment]
Existing hotkeys in the code so far (`wx-sdl2-display.c` and `wx-sdl2-display-win.c`):
```
Ctrl + End/NumPad1 - Release mouse
Ctrl + Alt + PageDown/NumPad3 - Toggle fullscreen
Ctrl + Alt + PageUp/NumPad9 - Take screenshot
```
For our stuff I suggest:
```
Ctrl + / + LeftArrow - Select previous CD in the queue
Ctrl + / + RightArrow - Select next CD in the queue
Ctrl + / + DownArrow - Load selected CD
```
```
Ctrl + . + LeftArrow - Select previous disk A in the queue
Ctrl + . + RightArrow - Select next disk A in the queue
Ctrl + . + DownArrow - Load selected disk A
```
```
Ctrl + , + LeftArrow - Select previous disk B in the queue
Ctrl + , + RightArrow - Select next disk B in the queue
Ctrl + , + DownArrow - Load selected disk B
```
PCem supports zip drives and cassettes, but for games those don't seem to be needed

**Comment by clementgallet** [comment]
Some comments regarding 9b02d13 so that I'm not forgetting anything:

- in the config file, specify `cdrom_path = path1;path2;path3;etc`
- set `cdrom_drive = 200` (which is the value of `CDROM_IMAGE`), so that PCem will load the image list and the first image from startup
- setting a list of images is incompatible with GUI option. Setting a CD image in the GUI will set a single image only, it is not possible to specify a list of images that way
- currently set to `Ctrl + . + Arrow` in the commit, because `Ctrl + / + Arrow` is buggy on my system (works with Down but not Left or Right)
- to view the CD swap in the log, you must compile without `--enable-release-build`. A log file will be created in `~/.pcem/logs/pcem.log`, which you can view with `tail -f`. A command is printed in the log when switching to prev/next CD image and when loading that image
- the CD swapping is done by the renderer thread (because it is the thread querying for events), as opposed to when it is selected from the GUI. I don't think it is a problem, I'm just mentioning it

**Comment by vadosnaprimer** [comment]
It would be highly desirable to have the image swap indication in release builds, for end users (first and foremost tasers, but also judges).

Also what's `tail -f`?

**Comment by clementgallet** [comment]
`tail` is to view the end of a text file, and `-f` updates the view continuously.
I'll add the image swap log in the terminal then.

**Comment by clementgallet** [comment]
Added floppy switch in 1f6d8c5. Add messages to `stdout` for CD/floppy switch and load. I modified a bit the hotkeys so that the one that is buggy for me controls floppy drive `b:`:

- Ctrl + Comma + Arrow: CD
- Ctrl + Period + Arrow: floppy a:
- Ctrl + Slash + Arrow: floppy b:

**Comment by slamotas** [comment]
It should be obvious but we should mention that the floppy paths should be specified in `disc_a = ` and `disc_b = ` in the config file.

I tested both floppy and CD swapping and it all works without a problem. I even tried recording a movie in libTAS with the hotkeys and it played back with the proper switching. Looks like we should be able to TAS multi-disk games with this, thank you!

I should mention that if you put an invalid path as one of the disks and try to load it, the drive becomes empty. This could be useful in obscure cases.

**Comment by vadosnaprimer** [comment]
Thank you guys!
